schema_version = 1

[package]
name = "libelf"
version = "0.196"
release = "2"
description = "libelf shared library for reading ELF files (from elfutils)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://sourceware.org/elfutils/ftp/0.196/elfutils-0.196.tar.bz2"
sha256 = "fd5cc6b77ad6773cac93cb3f415f9318ac3b3455eecf801f6b4a742c4f6c7209"

build_dependencies = [
    "zlib-dev >= 1.3.0",
    "pkgconf",
]

dependencies = [
    "zlib >= 1.3.0",
]

provides = [
    "libelf",
    "so:libelf.so.1",
]

prepare = [
]

build = [
    "CFLAGS=\"-O2 -Wno-error=format-nonliteral\" ./configure --prefix=/usr --disable-debuginfod --enable-libdebuginfod=dummy",
    "make -C lib -j$(nproc)",
    "make -C libelf -j$(nproc)",
]

install = [
    "make -C libelf install DESTDIR=$DESTDIR",
    "mkdir -p $DESTDIR/usr/lib/pkgconfig",
    "install -vm644 config/libelf.pc $DESTDIR/usr/lib/pkgconfig/",
    "rm -f $DESTDIR/usr/lib/libelf.a",
]
