schema_version = 1

[package]
name = "iana-etc"
version = "20260811"
release = "2"
description = "IANA /etc/services and /etc/protocols"
license = "custom:none"
channel = "system"

[source]
url = "https://github.com/Mic92/iana-etc/releases/download/20260811/iana-etc-20260811.tar.gz"
sha256 = "c2aef2efc628eb281eb070fef7119a5cef40a5682e33802b0c0230909ad4595c"

dependencies = []

provides = [
    "iana-etc"
]

prepare = []

build = []

install = [
    "mkdir -p $DESTDIR/etc",
    "cp services protocols $DESTDIR/etc/"
]
