schema_version = 1

[package]
name = "packaging"
version = "26.3"
release = "2"
description = "Python packaging core utilities"
license = "Apache-2.0 OR BSD-2-Clause"
channel = "system"

[source]
url = "https://files.pythonhosted.org/packages/7d/fa/3944b40b07da9ce895c0e6303a5ab7d53da063554f534556b134a54d6093/packaging-26.3.tar.gz"
sha256 = "94edc256424af38762eb31306eed28beb9f0efc50a8837492c9d6fd6004aed79"

dependencies = [
    "python >= 3.14.7",
    "flit-core >= 4.0.2"
]

build_dependencies = [
    "python >= 3.14.7",
    "flit-core >= 3.9.0"
]

provides = [
    "packaging"
]

prepare = []

build = [
    "python3 -m flit_core.wheel"
]

install = [
    "mkdir -p $DESTDIR/usr/lib/python3.14/site-packages",
    "python3 -c \"import sys, zipfile, glob; [zipfile.ZipFile(f).extractall(sys.argv[1]) for f in glob.glob('dist/*.whl')]\" $DESTDIR/usr/lib/python3.14/site-packages"
]
