schema_version = 1

[package]
name = "man-pages"
version = "6.18"
release = "2"
description = "Linux man pages"
license = "GPL-2.0-or-later AND BSD-3-Clause"
channel = "system"

[source]
url = "https://mirrors.kernel.org/pub/linux/docs/man-pages/man-pages-6.18.tar.xz"
sha256 = "c934fadc8b59748c68227a34f6581d2ddf8282b73cdcd52546c8cd88b74b24d1"

dependencies = []

provides = [
    "man-pages"
]

prepare = []

build = []

install = [
    "make -R prefix=/usr install DESTDIR=$DESTDIR"
]
