schema_version = 1

[package]
name = "tcl"
version = "8.6.18"
release = "2"
description = "Tool Command Language interpreter"
license = "TCL"
channel = "system"

[source]
url = "https://downloads.sourceforge.net/project/tcl/Tcl/8.6.18/tcl8.6.18-src.tar.gz"
sha256 = "14f9af32b1767ff718477a8f974ad03c34341097e6b43f4ce54644ee974e268e"

dependencies = [
]

build_dependencies = [
]

provides = [
    "tcl",
    "so:libtcl8.6.so",
]

prepare = [
]

build = [
    "cd unix && ./configure --prefix=/usr --mandir=/usr/share/man",
    "cd unix && make -j$(nproc)",
]

install = [
    "cd unix && make install DESTDIR=$DESTDIR",
    "cd unix && make install-private-headers DESTDIR=$DESTDIR",
    "ln -sfv tclsh8.6 $DESTDIR/usr/bin/tclsh",
    "ln -sfv libtcl8.6.so $DESTDIR/usr/lib/libtcl.so",
    "mv $DESTDIR/usr/share/man/man3/Thread.3 $DESTDIR/usr/share/man/man3/Tcl_Thread.3",
]
