schema_version = 1

[package]
name = "pcre2"
version = "10.47"
release = "2"
description = "pcre2grep, pcre2test and pcre2-config tools"
license = "BSD-3-Clause"
channel = "system"

[source]
url = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.bz2"
sha256 = "47fe8c99461250d42f89e6e8fdaeba9da057855d06eb7fc08d9ca03fd08d7bc7"

dependencies = [
    "pcre2-libs >= 10.47",
    "bzip2-libs >= 1.0.8",
    "zlib >= 1.3.2"
]

build_dependencies = [
    "bzip2-dev >= 1.0.8",
    "zlib-dev >= 1.3.2"
]

provides = [
    "pcre2"
]

prepare = []

build = [
    "./configure --prefix=/usr --enable-pcre2-16 --enable-pcre2-32 --enable-jit --disable-static",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
