schema_version = 1

[package]
name = "readline-dev"
version = "8.3"
release = "2"
description = "GNU Readline headers, pkg-config and linker symlink"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/readline/readline-8.3.tar.gz"
sha256 = "fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc"

dependencies = [
    "readline >= 8.3",
    "ncurses-dev >= 6.6"
]

provides = [
    "readline-dev"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --with-curses",
    "make -j$(nproc) SHLIB_LIBS=\"-lncursesw\""
]

install = [
    "make SHLIB_LIBS=\"-lncursesw\" install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f -name '*.so.*' -delete 2>/dev/null || true"
]
