schema_version = 1

[package]
name = "linux-zen-headers"
version = "7.1.9"
release = "2"
description = "Linux ZEN UAPI headers (bound to linux-zen 7.1.9)"
license = "GPL-2.0-only"
channel = "system"

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.1.9.tar.xz"
sha256 = "3271a4ae3897b38352980f2b0975bae61bca81c644d186221c5ae928bcc072b0"

dependencies = []

provides = [
    "linux-zen-headers",
    "linux-headers",
    "virtual/linux-headers"
]

prepare = []

build = [
    "make headers"
]

install = [
    "find usr/include -type f ! -name '*.h' -delete",
    "mkdir -p $DESTDIR/usr/include",
    "cp -rv usr/include/* $DESTDIR/usr/include/"
]
