schema_version = 1

[package]
name = "gmp-dev"
version = "6.3.0"
release = "2"
description = "GNU MP headers, pkg-config and linker symlink"
license = "LGPL-3.0-or-later OR GPL-2.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/gmp/gmp-6.3.0.tar.xz"
sha256 = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"

dependencies = [
    "gmp >= 6.3.0"
]

provides = [
    "gmp-dev"
]

prepare = []

build = [
    "CFLAGS=\"${CFLAGS:--O2} -std=gnu17\" ./configure --prefix=/usr --enable-cxx --disable-static --build=x86_64-pc-linux-gnu",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f -name '*.so.*' -delete 2>/dev/null || true"
]
