schema_version = 1

[package]
name = "procps-ng"
version = "4.0.7"
release = "2"
description = "Process and system monitoring utilities (ps, top, free)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://downloads.sourceforge.net/project/procps-ng/Production/procps-ng-4.0.7.tar.xz"
sha256 = "9d2021f47a4501c667862c9942a92d1953694b21d11bcd1702e83eb594e3d67d"

dependencies = [
    "procps-ng-libs >= 4.0.7",
    "ncurses-libs >= 6.6",
    "systemd-libs >= 261.2"
]

build_dependencies = [
    "pkgconf >= 3.0.5",
    "ncurses-dev >= 6.6"
]

provides = [
    "procps-ng"
]

prepare = []

build = [
    "./configure --prefix=/usr --docdir=/usr/share/doc/procps-ng-4.0.7 --disable-static --disable-kill --enable-watch8bit",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
