schema_version = 1

[package]
name = "tomlplusplus"
version = "3.4.0"
release = "2"
description = "toml++ compiled shared runtime library"
license = "MIT"
channel = "system"

[source]
url = "https://github.com/marzer/tomlplusplus/archive/refs/tags/v3.4.0.tar.gz"
sha256 = "8517f65938a4faae9ccf8ebb36631a38c1cadfb5efa85d9a72e15b9e97d25155"

dependencies = [
    "gcc-libs >= 15.3.0",
    "glibc >= 2.44"
]

provides = [
    "tomlplusplus",
    "so:libtomlplusplus.so.3"
]

prepare = []

build = [
    "g++ -fPIC -shared -O3 -std=c++20 -Iinclude src/toml.cpp -DTOML_SHARED_LIB=1 -DTOML_EXPORTING=1 -Wl,-soname,libtomlplusplus.so.3 -o libtomlplusplus.so.3.4.0",
    "ln -sf libtomlplusplus.so.3.4.0 libtomlplusplus.so.3"
]

install = [
    "mkdir -p $DESTDIR/usr/lib",
    "cp -d libtomlplusplus.so.3.4.0 libtomlplusplus.so.3 $DESTDIR/usr/lib/"
]
