schema_version = 1

[package]
name = "bash"
version = "5.3"
release = "3"
description = "The GNU Bourne Again SHell"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/bash/bash-5.3.tar.gz"
sha256 = "0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"

dependencies = [
    "readline >= 8.2.0",
    "ncurses >= 6.5",
]

build_dependencies = [
    "gettext >= 0.22",
]

provides = [
    "bash",
    "sh",
]

prepare = [
]

build = [
    "bash_cv_dev_fd=standard ./configure --prefix=/usr --without-bash-malloc --with-installed-readline",
    "make -j$(nproc)",
]

install = [
    "make install DESTDIR=$DESTDIR",
    "ln -sf bash $DESTDIR/usr/bin/sh",
    "rm -f $DESTDIR/usr/share/info/dir",
]
