schema_version = 1

[package]
name = "pkgconf"
version = "3.0.5"
release = "2"
description = "pkg-config compatible compiler/linker helper"
license = "ISC"
channel = "system"

[source]
url = "https://github.com/pkgconf/pkgconf/releases/download/pkgconf-3.0.5/pkgconf-3.0.5.tar.xz"
sha256 = "3acd3a8a3cce65a8d620321855d92fb602e026cbe8e13ee36bdec58483b59ace"

dependencies = [
    "glibc >= 2.44"
]

provides = [
    "pkgconf"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "ln -sf pkgconf $DESTDIR/usr/bin/pkg-config",
    "ln -sf pkgconf.1 $DESTDIR/usr/share/man/man1/pkg-config.1 2>/dev/null || true"
]
