schema_version = 1

[package]
name = "efivar"
version = "39"
release = "2"
description = "EFI variable tools and libraries"
license = "LGPL-2.1-or-later"
channel = "system"

[source]
url = "https://github.com/rhboot/efivar/archive/refs/tags/39.tar.gz"
sha256 = "c9edd15f2eeeea63232f3e669a48e992c7be9aff57ee22672ac31f5eca1609a6"

dependencies = [
    "glibc >= 2.44",
]

build_dependencies = [
    "gcc >= 15.3.0",
    "make >= 4.4",
]

provides = [
    "efivar",
    "so:libefiboot.so.1",
    "so:libefivar.so.1",
]

prepare = [
    "patch -Np1 -i $RECIPE_DIR/target-runner.patch",
]

build = [
    "SC_TARGET_RUNNER=\"$SC_BUILD_SYSROOT/usr/lib/@SC_DYNAMIC_LINKER@ --library-path $SC_BUILD_SYSROOT/usr/lib:$SC_BUILD_SYSROOT/usr/lib64:$SC_BUILD_SYSROOT/lib:$SC_BUILD_SYSROOT/lib64\" make ERRORS='' ENABLE_DOCS=0 -j1",
]

install = [
    "SC_TARGET_RUNNER=\"$SC_BUILD_SYSROOT/usr/lib/@SC_DYNAMIC_LINKER@ --library-path $SC_BUILD_SYSROOT/usr/lib:$SC_BUILD_SYSROOT/usr/lib64:$SC_BUILD_SYSROOT/lib:$SC_BUILD_SYSROOT/lib64\" make ERRORS='' ENABLE_DOCS=0 DESTDIR=$DESTDIR libdir=/usr/lib bindir=/usr/bin mandir=/usr/share/man includedir=/usr/include install -j1",
]
