schema_version = 1

[package]
name = "kbd"
version = "2.10.0"
release = "2"
description = "Keyboard and console utilities"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.10.0.tar.xz"
sha256 = "6e5ca4f8d76ee9e3a8db700b667f13e12aac9933828a64e1aaad93d26be9b479"

dependencies = [
    "linux-headers >= 7.1.9"
]

build_dependencies = [
    "linux-headers >= 7.1.9",
    "flex >= 2.6.4"
]

provides = [
    "kbd"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-vlock",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/share/doc/kbd/examples 2>/dev/null || true"
]
