schema_version = 1

[package]
name = "sclinux-boot"
version = "1.0.0"
release = "2"
description = "ShenChen Linux initramfs and systemd-boot integration"
license = "GPL-3.0-or-later"
channel = "system"

dependencies = [
    "coreutils >= 9.0",
    "findutils >= 4.9",
    "linux-zen >= 7.1.9",
    "lvm2 >= 2.03.42",
    "mkinitcpio >= 41.1",
    "systemd >= 261.2",
    "xfsprogs >= 7.1.1",
]

provides = [
    "sclinux-boot",
]

prepare = [
]

build = [
]

install = [
    "install -Dm755 $RECIPE_DIR/sclinux-update-boot.in $DESTDIR/usr/bin/sclinux-update-boot",
    "sed -i -e 's/@SYSTEMD_BOOT_EFI@/@SC_SYSTEMD_BOOT_EFI@/g' -e 's/@EFI_BOOT_NAME@/@SC_EFI_BOOT_NAME@/g' $DESTDIR/usr/bin/sclinux-update-boot",
    "install -Dm755 $RECIPE_DIR/90-sclinux-boot.install $DESTDIR/usr/lib/kernel/install.d/90-sclinux-boot.install",
    "install -d $DESTDIR/etc",
    "printf 'MODULES=()\nBINARIES=(/usr/bin/lvm /usr/bin/dmsetup)\nFILES=()\nHOOKS=(systemd modconf block lvm2 filesystems fsck)\nCOMPRESSION=\"zstd\"\n' > $DESTDIR/etc/mkinitcpio.conf",
    "install -d $DESTDIR/etc/kernel",
    "printf 'root=/dev/mapper/sclinux-root rd.lvm.lv=sclinux/root rw rootfstype=xfs console=@SC_KERNEL_CONSOLE@\n' > $DESTDIR/etc/kernel/cmdline",
]
