schema_version = 1

[package]
name = "flit-core"
version = "4.0.2"
release = "1"
description = "Python PEP 517 build backend (flit_core)"
license = "BSD-3-Clause"
channel = "system"

[source]
url = "https://files.pythonhosted.org/packages/46/ef/34533186e76c526d9ec17a1ad9a10c7354cbfb20f51583cc36dfe4bdccd0/flit_core-4.0.2.tar.gz"
sha256 = ""

dependencies = [
    "python >= 3.12.0",
]

build_dependencies = [
    "python >= 3.12.0",
]

provides = [
    "flit-core",
]

prepare = [
]

build = [
    "python3 -m flit_core.wheel",
]

install = [
    "python3 bootstrap_install.py --install-root=$DESTDIR dist/flit_core-*.whl",
]
