schema_version = 1

[package]
name = "glibc"
version = "2.44"
release = "3"
description = "The GNU C Library"
license = "LGPL-2.1-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.44.tar.xz"
sha256 = "37f600f2bef3c5e8300147059568b2a2e40a7ad6ccc65ce942556d49429cc667"

dependencies = [
    "linux-headers >= 6.10.0",
]

build_dependencies = [
    "bison >= 3.8",
    "python >= 3.12",
]

provides = [
    "glibc",
    "virtual/libc",
    "so:libc.so.6",
    "so:@SC_DYNAMIC_LINKER@",
]

prepare = [
    "mkdir -p build",
]

build = [
    'cd build && env -u CPATH -u LIBRARY_PATH CPPFLAGS= LDFLAGS= ../configure --prefix=/usr --with-headers="$SC_BUILD_SYSROOT/usr/include" --disable-profile --enable-kernel=4.19 --enable-stack-protector=strong --disable-nscd libc_cv_slibdir=/usr/lib',
    "cd build && env -u CPATH -u LIBRARY_PATH make -j$(nproc)",
]

install = [
    "cd build && env -u CPATH -u LIBRARY_PATH make install DESTDIR=$DESTDIR",
    "mkdir -p $DESTDIR/usr/lib/locale",
    "sed '/RTLDLIST/s@/usr@@g' -i $DESTDIR/usr/bin/ldd 2>/dev/null || true",
]
