schema_version = 1

[package]
name = "dbus"
version = "1.16.2"
release = "2"
description = "D-Bus message bus system (daemon and libdbus)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz"
sha256 = "0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"

dependencies = [
    "expat >= 2.6.0",
    "systemd >= 261.0",
]

build_dependencies = [
    "meson >= 1.5",
    "ninja >= 1.11",
]

provides = [
    "dbus",
    "so:libdbus-1.so.3",
]

prepare = [
]

build = [
    "mkdir build",
    "cd build && meson setup --prefix=/usr --libdir=lib --buildtype=release --wrap-mode=nofallback -Dsystemd_system_unitdir=/usr/lib/systemd/system -Dsystemd_user_unitdir=/usr/lib/systemd/user ..",
    "cd build && ninja -j$(nproc)",
]

install = [
    "cd build && DESTDIR=$DESTDIR ninja install",
    "ln -sfv /etc/machine-id $DESTDIR/var/lib/dbus",
]
