schema_version = 1

[package]
name = "nano"
version = "9.2"
release = "2"
description = "Pico editor clone"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/nano/nano-9.2.tar.xz"
sha256 = "05ecb99247b782e8a5b3a25ed4101dd034b0236902f7449bc9795b717642f7e9"

dependencies = [
    "ncurses-libs >= 6.6",
    "file-libs >= 5.48"
]

build_dependencies = [
    "ncurses-dev >= 6.6",
    "file-dev >= 5.48"
]

provides = [
    "nano",
    "editor"
]

prepare = []

build = [
    "./configure --prefix=/usr --sysconfdir=/etc --enable-utf8",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR"
]
