schema_version = 1

[package]
name = "zstd"
version = "1.5.7"
release = "2"
description = "Zstandard compression tool"
license = "BSD-3-Clause OR GPL-2.0-only"
channel = "system"

[source]
url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz"
sha256 = "eb33e51f49a15e023950cd7825ca74a4a2b43db8354825ac24fc1b7ee09e6fa3"

dependencies = [
    "zstd-libs >= 1.5.7"
]

provides = [
    "zstd"
]

prepare = []

build = [
    "make prefix=/usr -j$(nproc)"
]

install = [
    "make prefix=/usr install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
