schema_version = 1

[package]
name = "util-linux"
version = "2.42.2"
release = "2"
description = "Essential system utilities (mount, fdisk, login, su, ...)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.42/util-linux-2.42.2.tar.xz"
sha256 = "03a05d3adf9602ef128f2da05b84b3205ce60c351e5737c0370f74000679ce8a"

dependencies = [
    "util-linux-libs >= 2.42.2"
]

provides = [
    "util-linux"
]

prepare = []

build = [
    "./configure --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libdir=/usr/lib --sysconfdir=/etc --disable-static --without-python --without-systemd --disable-makeinstall-chown --without-bash-completion-dir --docdir=/usr/share/doc/util-linux-2.42.2",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib/pkgconfig",
    "rm -f $DESTDIR/usr/lib/libuuid.so* $DESTDIR/usr/lib/libblkid.so* $DESTDIR/usr/lib/libmount.so* $DESTDIR/usr/lib/libsmartcols.so*"
]
