schema_version = 1

[package]
name = "curl-libs"
version = "8.21.0"
release = "2"
description = "libcurl shared runtime library"
license = "curl"
channel = "system"

[source]
url = "https://curl.se/download/curl-8.21.0.tar.xz"
sha256 = "aa1b66a70eace83dc624508745646c08ae561de512ab403adffb93ac87fc72e6"

dependencies = [
    "openssl-libs >= 4.0.1",
    "zlib >= 1.3.2",
    "zstd-libs >= 1.5.7"
]

build_dependencies = [
    "openssl-dev >= 4.0.1",
    "zlib-dev >= 1.3.2",
    "zstd-dev >= 1.5.7",
    "pkgconf >= 3.0.5"
]

provides = [
    "curl-libs",
    "so:libcurl.so.4"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --with-openssl --with-zlib --with-zstd --without-brotli --without-nghttp2 --without-libpsl --without-libidn2",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var $DESTDIR/usr/lib/pkgconfig $DESTDIR/usr/lib/cmake 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f \\( -name '*.a' -o -name '*.la' \\) -delete 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 \\( -type l -o -type f \\) -name '*.so' ! -name '*.so.*' -delete 2>/dev/null || true"
]
