schema_version = 1

[package]
name = "mpdecimal"
version = "4.0.1"
release = "2"
description = "libmpdec/libmpdec++ shared runtime libraries"
license = "BSD-2-Clause"
channel = "system"

[source]
url = "https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.1.tar.gz"
sha256 = "96d33abb4bb0070c7be0fed4246cd38416188325f820468214471938545b1ac8"

dependencies = [
    "glibc >= 2.44"
]

provides = [
    "mpdecimal",
    "so:libmpdec.so.4",
    "so:libmpdec++.so.4"
]

prepare = []

build = [
    "./configure --prefix=/usr",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var $DESTDIR/usr/lib/pkgconfig $DESTDIR/usr/lib/cmake 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f \\( -name '*.a' -o -name '*.la' \\) -delete 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 \\( -type l -o -type f \\) -name '*.so' ! -name '*.so.*' -delete 2>/dev/null || true"
]
