schema_version = 1

[package]
name = "bison"
version = "3.8.2"
release = "2"
description = "Parser generator (yacc-compatible)"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/bison/bison-3.8.2.tar.xz"
sha256 = "9bba0214ccf7f1079c5d59210045227bcf619519840ebfa80cd3849cff5a5bf2"

dependencies = [
]

build_dependencies = [
]

provides = [
    "bison",
]

prepare = [
]

build = [
    "M4=m4 ./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2",
    "PREBISON=\"$SC_BUILD_SYSROOT/usr/lib/@SC_DYNAMIC_LINKER@ --library-path $SC_BUILD_SYSROOT/usr/lib:$SC_BUILD_SYSROOT/usr/lib64:$SC_BUILD_SYSROOT/lib:$SC_BUILD_SYSROOT/lib64\" make -j$(nproc)",
]

install = [
    "PREBISON=\"$SC_BUILD_SYSROOT/usr/lib/@SC_DYNAMIC_LINKER@ --library-path $SC_BUILD_SYSROOT/usr/lib:$SC_BUILD_SYSROOT/usr/lib64:$SC_BUILD_SYSROOT/lib:$SC_BUILD_SYSROOT/lib64\" make install DESTDIR=$DESTDIR",
]
