schema_version = 1

[package]
name = "linux-headers"
version = "7.2"
release = "1"
description = "Linux kernel UAPI headers for userspace"
license = "GPL-2.0-only"
channel = "system"

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.2.tar.xz"
sha256 = "f9fef3d14c0df53819026f4be74459835c2a0b0dcbf5b5bbd9ea19f0829402b3"

dependencies = [
]

provides = [
    "linux-headers",
]

prepare = [
]

build = [
    "make headers",
]

install = [
    "find usr/include -type f ! -name '*.h' -delete",
    "mkdir -p $DESTDIR/usr/include",
    "cp -rv usr/include/* $DESTDIR/usr/include/",
]
