schema_version = 1

[package]
name = "gettext"
version = "1.0"
release = "2"
description = "GNU i18n tools (gettext, msgfmt, xgettext, ...)"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://ftp.gnu.org/gnu/gettext/gettext-1.0.tar.xz"
sha256 = "71132a3fb71e68245b8f2ac4e9e97137d3e5c02f415636eb508ae607bc01add7"

dependencies = [
    "gettext-libs >= 1.0"
]

provides = [
    "gettext"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/gettext-1.0",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
