schema_version = 1

[package]
name = "fastfetch"
version = "2.67.1"
release = "2"
description = "Fast, highly customizable system information tool"
license = "MIT"
channel = "system"

[source]
url = "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.67.1.tar.gz"
sha256 = "52489550d1fdeac8bde8b3442064e3bc78d28fda752a171dc46a6cd97454f237"

dependencies = [
    "glibc >= 2.44",
    "zlib >= 1.3.2",
    "sqlite-libs >= 3.53.4"
]

build_dependencies = [
    "cmake >= 4.4.2",
    "pkgconf >= 3.0.5",
    "zlib-dev >= 1.3.2",
    "sqlite-dev >= 3.53.4"
]

provides = [
    "fastfetch"
]

prepare = []

build = [
    "cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=OFF",
    "cmake --build build -j$(nproc)"
]

install = [
    "DESTDIR=$DESTDIR cmake --install build"
]
