schema_version = 1

[package]
name = "binutils"
version = "2.47"
release = "2"
description = "GNU binary utilities in gcc toolchain slot"
license = "GPL-3.0-or-later"
channel = "toolchain/gcc:15"

[source]
url = "https://mirrors.kernel.org/gnu/binutils/binutils-2.47.tar.xz"
sha256 = "154ab23b60070e8f27013c22977f1129425d67d1e8acd6e13010e617811e4cff"

dependencies = [
    "zlib >= 1.3.2",
    "zstd-libs >= 1.5.7",
    "gmp >= 6.3.0"
]

build_dependencies = [
    "zlib-dev >= 1.3.2",
    "zstd-dev >= 1.5.7",
    "gmp-dev >= 6.3.0"
]

provides = [
    "binutils",
    "so:libbfd-2.47.so",
    "so:libctf.so.0"
]

prepare = [
    "mkdir -p build"
]

build = [
    "cd build && ../configure --prefix=/opt/channels/gcc/15 --sysconfdir=/etc --enable-gold --enable-ld=default --enable-plugins --enable-shared --disable-werror --enable-64-bit-bfd --with-system-zlib --enable-default-hash-style=gnu --without-debuginfod --disable-gprofng",
    "cd build && make tooldir=/opt/channels/gcc/15 -j$(nproc)"
]

install = [
    "cd build && make tooldir=/opt/channels/gcc/15 install DESTDIR=$DESTDIR",
    "rm -fv $DESTDIR/opt/channels/gcc/15/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a 2>/dev/null || true"
]
