schema_version = 1

[package]
name = "acl"
version = "2.4.0"
release = "2"
description = "Access Control List tools (getfacl, setfacl)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://download-mirror.savannah.gnu.org/releases/acl/acl-2.4.0.tar.xz"
sha256 = "e661131456d2708a01c614a0f400e11d7d1bfaeb6f3e74b75bb980b72f0161a3"

dependencies = [
    "acl-libs >= 2.4.0",
    "attr-libs >= 2.6.0"
]

provides = [
    "acl"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --sysconfdir=/etc --docdir=/usr/share/doc/acl-2.4.0",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
