schema_version = 1

[package]
name = "util-linux-libs"
version = "2.42.2"
release = "2"
description = "libuuid/libblkid/libmount/libsmartcols shared libraries and headers"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.42/util-linux-2.42.2.tar.xz"
sha256 = "03a05d3adf9602ef128f2da05b84b3205ce60c351e5737c0370f74000679ce8a"

dependencies = [
]

provides = [
    "util-linux-libs",
    "so:libuuid.so.1",
    "so:libblkid.so.1",
    "so:libmount.so.1",
    "so:libsmartcols.so.1",
]

prepare = [
]

build = [
    "./configure --prefix=/usr --libdir=/usr/lib --disable-static --without-python --without-systemd --disable-all-programs --enable-libmount --enable-libuuid --enable-libblkid --enable-libsmartcols",
    "make -j$(nproc)",
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/share/locale $DESTDIR/usr/share/man",
    "rm -f $DESTDIR/usr/lib/libuuid.la $DESTDIR/usr/lib/libblkid.la $DESTDIR/usr/lib/libmount.la $DESTDIR/usr/lib/libsmartcols.la",
]
