schema_version = 1

[package]
name = "libseccomp"
version = "2.6.0"
release = "2"
description = "libseccomp shared runtime library"
license = "LGPL-2.1-only"
channel = "system"

[source]
url = "https://github.com/seccomp/libseccomp/releases/download/v2.6.0/libseccomp-2.6.0.tar.gz"
sha256 = "83b6085232d1588c379dc9b9cae47bb37407cf262e6e74993c61ba72d2a784dc"

dependencies = [
    "glibc >= 2.44"
]

build_dependencies = [
    "gperf >= 3.3"
]

provides = [
    "libseccomp",
    "so:libseccomp.so.2"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var $DESTDIR/usr/lib/pkgconfig $DESTDIR/usr/lib/cmake 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f \\( -name '*.a' -o -name '*.la' \\) -delete 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 \\( -type l -o -type f \\) -name '*.so' ! -name '*.so.*' -delete 2>/dev/null || true"
]
