schema_version = 1

[package]
name = "diffutils"
version = "3.12"
release = "2"
description = "GNU diff and cmp"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/diffutils/diffutils-3.12.tar.xz"
sha256 = "7c8b7f9fc8609141fdea9cece85249d308624391ff61dedaf528fcb337727dfd"

dependencies = []

build_dependencies = []

provides = [
    "diffutils"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-nls",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR"
]
