schema_version = 1

[package]
name = "libinih"
version = "61"
release = "2"
description = "inih INI file parser runtime library"
license = "BSD-3-Clause"
channel = "system"

[source]
url = "https://github.com/benhoyt/inih/archive/refs/tags/r61.tar.gz"
sha256 = "7caf26a2202a4ca689df3fe4175dfa74e0faa18fcca07331bba934fd0ecb8f12"

dependencies = [
    "glibc >= 2.44"
]

build_dependencies = [
    "meson >= 1.12.0",
    "ninja >= 1.13.2"
]

provides = [
    "libinih",
    "so:libinih.so.0"
]

prepare = []

build = [
    "meson setup build --prefix=/usr --buildtype=release -Ddefault_library=shared -Ddistro_install=true",
    "ninja -C build -j$(nproc)"
]

install = [
    "DESTDIR=$DESTDIR ninja -C build install",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var $DESTDIR/usr/lib/pkgconfig $DESTDIR/usr/lib/cmake 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f \\( -name '*.a' -o -name '*.la' \\) -delete 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 \\( -type l -o -type f \\) -name '*.so' ! -name '*.so.*' -delete 2>/dev/null || true"
]
