schema_version = 1

[package]
name = "libarchive-dev"
version = "3.8.9"
release = "2"
description = "libarchive headers, pkg-config and linker symlink"
license = "BSD-2-Clause"
channel = "system"

[source]
url = "https://github.com/libarchive/libarchive/releases/download/v3.8.9/libarchive-3.8.9.tar.xz"
sha256 = "888c934f9d95648ecb9163dc8e23ab80a476ecb81a8f1154704a227b5b676dde"

dependencies = [
    "libarchive-libs >= 3.8.9",
    "openssl-dev >= 4.0.1",
    "zlib-dev >= 1.3.2",
    "zstd-dev >= 1.5.7",
    "xz-dev >= 5.8.3",
    "bzip2-dev >= 1.0.8",
    "acl-dev >= 2.4.0",
    "attr-dev >= 2.6.0"
]

build_dependencies = [
    "pkgconf >= 3.0.5"
]

provides = [
    "libarchive-dev"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --without-xml2 --with-expat --without-cng --with-openssl --with-zlib --with-bz2lib --with-lzma --with-zstd",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f -name '*.so.*' -delete 2>/dev/null || true"
]
