schema_version = 1

[package]
name = "man-db"
version = "2.13.1"
release = "3"
description = "Manual page browsing utilities (man, mandb)"
license = "GPL-2.0-or-later"
channel = "system"

[source]
url = "https://download.savannah.gnu.org/releases/man-db/man-db-2.13.1.tar.xz"
sha256 = "8afebb6f7eb6bb8542929458841f5c7e6f240e30c86358c1fbcefbea076c87d9"

dependencies = [
    "libpipeline >= 1.5.0",
    "gdbm >= 1.23",
    "groff >= 1.23.0",
    "less >= 590",
    "xz-libs >= 5.6.0",
]

provides = [
    "man-db",
]

prepare = [
    "sed -i '/SUBDIRS/s/manual//' Makefile.in",
]

build = [
    "./configure --prefix=/usr --sbindir=/usr/bin --docdir=/usr/share/doc/man-db-2.13.1 --sysconfdir=/etc --disable-setuid --enable-cache-owner=bin --with-browser=/usr/bin/lynx --with-vgrind=/usr/bin/vgrind --with-grap=/usr/bin/grap --with-systemdtmpfilesdir=/usr/lib/tmpfiles.d --with-systemdsystemunitdir=/usr/lib/systemd/system --disable-manual",
    "make -j$(nproc)",
]

install = [
    "make install DESTDIR=$DESTDIR",
]
