schema_version = 1

[package]
name = "m4"
version = "1.4.21"
release = "2"
description = "GNU macro processor"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/m4/m4-1.4.21.tar.xz"
sha256 = "f25c6ab51548a73a75558742fb031e0625d6485fe5f9155949d6486a2408ab66"

dependencies = []

build_dependencies = []

provides = [
    "m4"
]

prepare = []

build = [
    "./configure --prefix=/usr",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR"
]
