schema_version = 1

[package]
name = "groff"
version = "1.24.1"
release = "2"
description = "GNU troff"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://ftpmirror.gnu.org/groff/groff-1.24.1.tar.gz"
sha256 = "74e2819795b6aff431aeac983d63a9c8968eeaba2a2eba7df8ba4c7b41e7cfd8"

dependencies = []

build_dependencies = [
    "perl >= 5.44.0"
]

provides = [
    "groff"
]

prepare = []

build = [
    "./configure --prefix=/usr",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR"
]
