schema_version = 1

[package]
name = "cmake"
version = "3.31.6"
release = "4"
description = "Cross-platform open-source build system"
license = "BSD-3-Clause"
channel = "system"

[source]
url = "https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6.tar.gz"
sha256 = "653427f0f5014750aafff22727fb2aa60c6c732ca91808cfb78ce22ddd9e55f0"

dependencies = [
    "glibc >= 2.44",
    "openssl-libs >= 4.0.1",
    "zlib >= 1.3.0",
    "bzip2-libs >= 1.0.8",
    "xz-libs >= 5.8.0",
    "zstd-libs >= 1.5.0",
    "curl >= 8.0.0",
    "expat >= 2.6.0",
    "libarchive >= 3.7.0",
]

build_dependencies = [
    "openssl-dev >= 4.0.1",
    "zlib-dev >= 1.3.0",
    "pkgconf >= 2.0.0",
]

provides = [
    "cmake",
]

prepare = [
    "chmod +x ../run-bootstrap-cmake.sh",
    "sed -i -e 's#^  \\./${TMPFILE}$#  ../../run-bootstrap-cmake.sh --direct @SC_DYNAMIC_LINKER@ \"./${TMPFILE}\"#' -e 's#^  \\./test$#  ../../../run-bootstrap-cmake.sh --direct @SC_DYNAMIC_LINKER@ \"./test\"#' bootstrap",
    "sed -i 's#^\"${cmake_bootstrap_dir}/cmake\" #../run-bootstrap-cmake.sh @SC_DYNAMIC_LINKER@ \"${cmake_bootstrap_dir}/cmake\" #' bootstrap",
]

build = [
    "env -u CPATH CFLAGS=\"$CFLAGS -fpermissive\" CXXFLAGS=\"$CXXFLAGS -fpermissive\" ./bootstrap --prefix=/usr --parallel=$(nproc) --system-curl --system-zlib --system-bzip2 --system-zstd --system-liblzma --system-libarchive --system-expat --no-system-jsoncpp --no-system-librhash --no-system-cppdap",
    "env -u CPATH make -j$(nproc)",
]

install = [
    "env -u CPATH DESTDIR=\"$DESTDIR\" ../run-bootstrap-cmake.sh --direct @SC_DYNAMIC_LINKER@ bin/cmake -P cmake_install.cmake",
]
