schema_version = 1

[package]
name = "base"
version = "2.0.0"
release = "2"
description = "sclinux Base System Meta-Package (Stage 2)"
license = "GPL-3.0-or-later"
channel = "system"

dependencies = [
    "os-release",
    "base-files",
    "linux-headers >= 7.1.9",
    "glibc",
    "glibc-dev",
    "zlib",
    "zlib-dev",
    "bzip2",
    "bzip2-libs",
    "bzip2-dev",
    "xz",
    "xz-libs",
    "xz-dev",
    "zstd",
    "zstd-libs",
    "zstd-dev",
    "lz4",
    "lz4-libs",
    "lz4-dev",
    "lzo",
    "lzo-dev",
    "file",
    "file-libs",
    "file-dev",
    "m4",
    "ncurses",
    "ncurses-libs",
    "ncurses-dev",
    "ncurses-terminfo",
    "readline",
    "readline-dev",
    "sed",
    "pcre2",
    "pcre2-libs",
    "pcre2-dev",
    "grep",
    "gawk",
    "diffutils",
    "findutils",
    "tar",
    "gzip",
    "patch",
    "make",
    "bash",
    "attr",
    "attr-libs",
    "attr-dev",
    "acl",
    "acl-libs",
    "acl-dev",
    "libcap",
    "libcap-libs",
    "libcap-dev",
    "libseccomp",
    "libseccomp-dev",
    "coreutils",
    "gmp",
    "gmp-dev",
    "mpfr",
    "mpfr-dev",
    "mpc",
    "mpc-dev",
    "isl",
    "isl-dev",
    "binutils",
    "gcc",
    "gcc-libs",
    "xmake",
    "lmdb",
    "lmdb-dev",
    "openssl",
    "openssl-libs",
    "openssl-dev",
    "curl",
    "curl-libs",
    "curl-dev",
    "tomlplusplus",
    "tomlplusplus-dev",
    "sage",
    "util-linux",
    "util-linux-libs",
    "util-linux-dev",
    "e2fsprogs",
    "e2fsprogs-libs",
    "e2fsprogs-dev",
    "xfsprogs",
    "dosfstools",
    "btrfs-progs",
    "man-pages",
    "iana-etc",
    "pkgconf",
    "bc",
    "flex",
    "bison",
    "texinfo",
    "libtool",
    "autoconf",
    "automake",
    "gdbm",
    "gdbm-libs",
    "gdbm-dev",
    "gperf",
    "gettext",
    "gettext-libs",
    "gettext-dev",
    "tcl",
    "tcl-libs",
    "tcl-dev",
    "expect",
    "dejagnu",
    "perl",
    "perl-libs",
    "libffi",
    "libffi-dev",
    "sqlite",
    "sqlite-libs",
    "sqlite-dev",
    "mpdecimal",
    "mpdecimal-dev",
    "python",
    "python-libs",
    "python-dev",
    "flit-core",
    "packaging",
    "wheel",
    "setuptools",
    "meson",
    "ninja",
    "expat",
    "expat-libs",
    "expat-dev",
    "libpipeline",
    "libpipeline-dev",
    "libelf",
    "libelf-dev",
    "libxcrypt",
    "libxcrypt-dev",
    "libarchive",
    "libarchive-libs",
    "libarchive-dev",
    "libinih",
    "libinih-dev",
    "userspace-rcu",
    "userspace-rcu-dev",
    "groff",
    "markupsafe",
    "jinja2",
    "psmisc",
    "inetutils",
    "less",
    "iproute2",
    "kbd",
    "procps-ng",
    "procps-ng-libs",
    "procps-ng-dev",
    "shadow",
    "kmod",
    "kmod-libs",
    "kmod-dev",
    "systemd-libs",
    "systemd-udev",
    "systemd",
    "systemd-networkd",
    "systemd-resolved",
    "systemd-timesyncd",
    "systemd-dev",
    "dbus",
    "dbus-libs",
    "dbus-dev",
    "man-db",
    "which",
    "grub"
]

provides = [
    "base"
]

prepare = []

build = []

install = []
