schema_version = 1

[package]
name = "binutils"
version = "2.47"
release = "4"
description = "GNU binary utilities (ld, as, ar, nm, objcopy, strip, etc.)"
license = "GPL-3.0-or-later"
channel = "toolchain/gcc:15"

[source]
url = "https://mirrors.kernel.org/gnu/binutils/binutils-2.47.tar.xz"
sha256 = "154ab23b60070e8f27013c22977f1129425d67d1e8acd6e13010e617811e4cff"

dependencies = [
]

provides = [
    "binutils",
    "so:libbfd-2.47.so",
    "so:libctf.so.0",
]

prepare = [
    "mkdir -p build",
]

build = [
    "cd build && ../configure --prefix=/opt/channels/gcc/15 --sysconfdir=/etc --enable-gold --enable-ld=default --enable-plugins --enable-shared --disable-werror --enable-64-bit-bfd --with-system-zlib --enable-default-hash-style=gnu --without-debuginfod --disable-gprofng",
    "cd build && make tooldir=/opt/channels/gcc/15 -j$(nproc)",
]

install = [
    "cd build && make tooldir=/opt/channels/gcc/15 install DESTDIR=$DESTDIR",
    "linker_alias=\"$(printf '%s\\n' '@SC_GNU_TRIPLET@' | sed -e 's/-pc-/-/' -e 's/-unknown-/-/')-ld\"; ln -sf ld \"$DESTDIR/opt/channels/gcc/15/bin/$linker_alias\"",
    "rm -fv $DESTDIR/opt/channels/gcc/15/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a 2>/dev/null || true",
    "rm -f $DESTDIR/opt/channels/gcc/15/share/info/dir",
]
