schema_version = 1

[package]
name = "gawk"
version = "5.4.1"
release = "2"
description = "GNU awk"
license = "GPL-3.0-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/gawk/gawk-5.4.1.tar.xz"
sha256 = "07f6f7342b7febe4313fc2c2542ad93d64fe20ad8717200109f105a826f5fd37"

dependencies = []

build_dependencies = []

provides = [
    "gawk",
    "awk"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-nls",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "ln -sf gawk $DESTDIR/usr/bin/awk"
]
