schema_version = 1

[package]
name = "openssl-dev"
version = "4.0.1"
release = "2"
description = "OpenSSL headers, pkg-config and unversioned .so"
license = "Apache-2.0"
channel = "system"

[source]
url = "https://www.openssl.org/source/openssl-4.0.1.tar.gz"
sha256 = "2db3f3a0d6ea4b59e1f094ace2c8cd536dffb87cdc39084c5afa1e6f7f37dd09"

dependencies = [
    "openssl-libs >= 4.0.1"
]

build_dependencies = [
    "zlib-dev >= 1.3.2"
]

provides = [
    "openssl-dev"
]

prepare = []

build = [
    "./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic enable-deprecated enable-tls1-method enable-tls1_1-method",
    "make -j$(nproc)"
]

install = [
    "make INSTALL_LIBS= MANSUFFIX=ssl install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/lib/engines-* $DESTDIR/usr/lib/ossl-modules",
    "rm -rf $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/usr/share $DESTDIR/etc $DESTDIR/var 2>/dev/null || true",
    "find $DESTDIR/usr/lib $DESTDIR/usr/lib64 -type f -name '*.so.*' -delete 2>/dev/null || true"
]
