schema_version = 1

[package]
name = "sage"
version = "0.2.0"
release = "11"
description = "Universal Multi-Layer Linux Package Manager"
license = "BSD-2-Clause"
channel = "system"

dependencies = [
    "lmdb >= 0.9.30",
    "zstd-libs >= 1.5.0",
    "curl >= 8.0.0",
    "gcc-libs >= 15.3.0",
]

build_dependencies = [
    "gcc >= 15.3.0",
    "tomlplusplus >= 3.4.0",
    "xmake >= 3.0.0",
]

provides = [
    "sage",
]

prepare = [
    "patch -p1 < \"$RECIPE_DIR/sage-bootstrap-install-integrity.patch\"",
]

build = [
    "XMAKE_ROOT=y XMAKE_STATS=false xmake f -c -m release -y --ldflags=\"$LDFLAGS\"",
    "XMAKE_ROOT=y XMAKE_STATS=false xmake -y",
]

install = [
    "XMAKE_ROOT=y XMAKE_STATS=false xmake install -o \"$DESTDIR/usr\" -y",
]

[source]
url = "https://codeload.github.com/antinomie1/sage/tar.gz/3904a73cde2f88923e8e4aab065eeb5bd62f15b3"
sha256 = "c57ff494a74762ecbcbbef3b734dc1fce185d778ff883798ef88914924b0b4db"
