schema_version = 1

[package]
name = "sage"
version = "0.2.0"
release = "1"
description = "Universal Multi-Layer Linux Package Manager"
license = "BSD-2-Clause"
channel = "system"

dependencies = [
    "lmdb >= 0.9.30",
    "zstd-libs >= 1.5.0",
    "curl >= 8.0.0",
    "gcc-libs >= 15.3.0",
]

build_dependencies = [
    "gcc >= 15.3.0",
    "tomlplusplus >= 3.4.0",
    "xmake >= 3.0.0",
]

provides = [
    "sage",
]

prepare = [
]

build = [
    "XMAKE_ROOT=y XMAKE_STATS=false xmake f -c -m release -y --ldflags=\"$LDFLAGS\"",
    "XMAKE_ROOT=y XMAKE_STATS=false xmake -y",
]

install = [
    "XMAKE_ROOT=y XMAKE_STATS=false xmake install -o \"$DESTDIR/usr\" -y",
    "install -Dm755 ../shc \"$DESTDIR/usr/bin/shc\"",
]

[source]
url = "https://codeload.github.com/sclinuxdev/sage/tar.gz/829bd197ccb3f923083908835bb4c5ed93f8e790"
sha256 = "78993c8bd419311ecc79e1af2fcc6d2ba870d406431571d802f2f745d6d34687"
