schema_version = 1

[package]
name = "glibc-dev"
version = "2.44"
release = "2"
description = "GNU C Library headers, static libraries and linker scripts"
license = "LGPL-2.1-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.44.tar.xz"
sha256 = "37f600f2bef3c5e8300147059568b2a2e40a7ad6ccc65ce942556d49429cc667"

dependencies = [
    "glibc >= 2.44",
    "linux-headers >= 7.1.9"
]

build_dependencies = []

provides = [
    "glibc-dev"
]

prepare = [
    "rm -rf build && mkdir -p build"
]

build = [
    "cd build && ../configure --prefix=/usr --enable-kernel=4.19 --enable-stack-protector=strong --disable-profile --disable-werror --without-gd libc_cv_slibdir=/usr/lib",
    "cd build && make -j$(nproc)"
]

install = [
    "cd build && make install DESTDIR=$DESTDIR",
    "rm -f $DESTDIR/usr/lib/libc.so.6 $DESTDIR/usr/lib/ld-linux*.so.*",
    "rm -rf $DESTDIR/usr/bin $DESTDIR/usr/sbin $DESTDIR/etc $DESTDIR/var $DESTDIR/usr/share"
]
