schema_version = 1

[package]
name = "lz4"
version = "1.10.0"
release = "2"
description = "lz4 extremely fast compression tool"
license = "BSD-2-Clause"
channel = "system"

[source]
url = "https://github.com/lz4/lz4/archive/refs/tags/v1.10.0.tar.gz"
sha256 = "537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"

dependencies = [
    "lz4-libs >= 1.10.0"
]

provides = [
    "lz4"
]

prepare = []

build = [
    "make prefix=/usr -j$(nproc)"
]

install = [
    "make prefix=/usr install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
