schema_version = 1

[package]
name = "bc"
version = "7.0.3"
release = "2"
description = "Arbitrary precision numeric processing language"
license = "BSD-2-Clause"
channel = "system"

[source]
url = "https://github.com/gavinhoward/bc/releases/download/7.0.3/bc-7.0.3.tar.xz"
sha256 = "91eb74caed0ee6655b669711a4f350c25579778694df248e28363318e03c7fc4"

dependencies = [
    "readline >= 8.3"
]

build_dependencies = [
    "readline-dev >= 8.3"
]

provides = [
    "bc"
]

prepare = []

build = [
    "CC=gcc CFLAGS=\"-std=gnu11 -O3\" ./configure --prefix=/usr -G -O3",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR"
]
