#!/bin/bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: $0 ROOTFS OUTPUT.raw" >&2
    exit 2
fi

rootfs=$(readlink -f "$1")
output=$(readlink -m "$2")
disk_size=${SCLINUX_DISK_SIZE:-16G}
root_size=${SCLINUX_ROOT_SIZE:-10G}
home_size=${SCLINUX_HOME_SIZE:-4G}
vg_name=vg0
loop_device=
mount_root=
vg_active=false

target() {
    chroot "$rootfs" /usr/bin/env -u LANG -u LANGUAGE -u LC_ALL \
        PATH=/usr/bin:/bin "$@"
}

cleanup() {
    set +e
    if [ -n "$mount_root" ]; then
        mountpoint -q "$mount_root/boot/efi" && umount "$mount_root/boot/efi"
        mountpoint -q "$mount_root/home" && umount "$mount_root/home"
        mountpoint -q "$mount_root" && umount "$mount_root"
        rmdir "$mount_root" 2>/dev/null || true
    fi
    if [ "$vg_active" = true ]; then
        target vgchange --activate n "$vg_name" >/dev/null 2>&1 || true
    fi
    if [ -n "$loop_device" ]; then
        losetup --detach "$loop_device" 2>/dev/null || true
    fi
    mountpoint -q "$rootfs/run" && umount -R "$rootfs/run"
    mountpoint -q "$rootfs/dev" && umount -R "$rootfs/dev"
    mountpoint -q "$rootfs/sys" && umount -R "$rootfs/sys"
    mountpoint -q "$rootfs/proc" && umount -R "$rootfs/proc"
}
trap cleanup EXIT

if [ ! -d "$rootfs/usr" ] || [ ! -x "$rootfs/usr/bin/sgdisk" ]; then
    echo "error: ROOTFS is not a complete SCLinux root: $rootfs" >&2
    exit 2
fi
if [ -e "$output" ]; then
    echo "error: refusing to overwrite existing image: $output" >&2
    exit 2
fi

install -d "$rootfs/dev" "$rootfs/proc" "$rootfs/run" "$rootfs/sys" \
    "$(dirname "$output")"
mount -t proc proc "$rootfs/proc"
mount --rbind /sys "$rootfs/sys"
mount --make-rslave "$rootfs/sys"
mount --rbind /dev "$rootfs/dev"
mount --make-rslave "$rootfs/dev"
mount --rbind /run "$rootfs/run"
mount --make-rslave "$rootfs/run"

for command in sgdisk partx pvcreate vgcreate lvcreate vgchange mkfs.xfs mkfs.fat blkid; do
    if ! target /usr/bin/test -x "/usr/bin/$command"; then
        echo "error: required image tool is missing from ROOTFS: $command" >&2
        exit 2
    fi
done

truncate --size "$disk_size" "$output"
loop_device=$(losetup --find --show "$output")
target sgdisk --zap-all "$loop_device"
target sgdisk \
    --new=1:2048:+1G --typecode=1:EF00 --change-name=1:"ShenChen EFI" \
    --new=2:0:0 --typecode=2:8E00 --change-name=2:"ShenChen LVM" \
    "$loop_device"
losetup --detach "$loop_device"
loop_device=$(losetup --find --show --partscan "$output")
target partx --add "$loop_device" 2>/dev/null || true

esp_partition=${loop_device}p1
lvm_partition=${loop_device}p2
loop_name=${loop_device#/dev/}
for partition_number in 1 2; do
    partition=/dev/${loop_name}p${partition_number}
    partition_dev=/sys/class/block/${loop_name}p${partition_number}/dev
    if [ ! -b "$partition" ] && [ -r "$partition_dev" ]; then
        IFS=: read -r major minor < "$partition_dev"
        mknod "$partition" b "$major" "$minor"
    fi
done
for _ in $(seq 1 50); do
    [ -b "$esp_partition" ] && [ -b "$lvm_partition" ] && break
    sleep 0.1
done
if [ ! -b "$esp_partition" ] || [ ! -b "$lvm_partition" ]; then
    echo "error: loop partitions did not appear for $loop_device" >&2
    exit 1
fi

target pvcreate --yes --force "$lvm_partition"
target vgcreate "$vg_name" "$lvm_partition"
target lvcreate --yes --type thin-pool --extents 90%FREE --name pool "$vg_name"
target lvcreate --yes --virtualsize "$root_size" --thinpool "$vg_name/pool" --name root
target lvcreate --yes --virtualsize "$home_size" --thinpool "$vg_name/pool" --name home
vg_active=true

root_device=/dev/mapper/${vg_name}-root
home_device=/dev/mapper/${vg_name}-home
target mkfs.xfs -f -L SCLINUX_ROOT "$root_device"
target mkfs.xfs -f -L SCLINUX_HOME "$home_device"
target mkfs.fat -F 32 -n SCLINUX_EFI "$esp_partition"

mount_root=$(mktemp -d /tmp/sclinux-image.XXXXXX)
mount "$root_device" "$mount_root"
install -d "$mount_root/home" "$mount_root/boot/efi"
mount "$home_device" "$mount_root/home"
mount "$esp_partition" "$mount_root/boot/efi"

tar --acls --xattrs --numeric-owner --one-file-system \
    --exclude=./dev/\* --exclude=./proc/\* --exclude=./run/\* --exclude=./sys/\* \
    -C "$rootfs" -cf - . | \
    tar --acls --xattrs --numeric-owner -C "$mount_root" -xf -

root_uuid=$(target blkid -s UUID -o value "$root_device")
home_uuid=$(target blkid -s UUID -o value "$home_device")
esp_uuid=$(target blkid -s UUID -o value "$esp_partition")
printf '%s\n' \
    '# /etc/fstab: generated by tools/assemble-image.sh' \
    "UUID=$root_uuid / xfs defaults 0 1" \
    "UUID=$home_uuid /home xfs defaults 0 2" \
    "UUID=$esp_uuid /boot/efi vfat umask=0077 0 2" \
    > "$mount_root/etc/fstab"

sync
echo "assembled $output"
