#!/bin/bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: $0 ROOTFS.tar[.zst] OUTPUT.qcow2" >&2
    exit 2
fi

rootfs_archive=$(readlink -f "$1")
output=$(readlink -m "$2")
disk_size=${SCLINUX_DISK_SIZE:-16G}
root_size=${SCLINUX_ROOT_SIZE:-10G}
home_size=${SCLINUX_HOME_SIZE:-4G}
temporary_tar=
temporary_fstab=
completed=false

cleanup() {
    if [ -n "$temporary_tar" ]; then
        rm -f "$temporary_tar"
    fi
    if [ -n "$temporary_fstab" ]; then
        rm -f "$temporary_fstab"
    fi
    if [ "$completed" != true ]; then
        rm -f "$output"
    fi
}
trap cleanup EXIT

if [ ! -f "$rootfs_archive" ]; then
    echo "error: rootfs archive does not exist: $rootfs_archive" >&2
    exit 2
fi
if [ -e "$output" ]; then
    echo "error: refusing to overwrite existing image: $output" >&2
    exit 2
fi
for command in guestfish qemu-img; do
    if ! command -v "$command" >/dev/null; then
        echo "error: required image tool is missing: $command" >&2
        exit 2
    fi
done

if [[ "$rootfs_archive" = *.zst ]]; then
    temporary_tar=$(mktemp "$(dirname "$rootfs_archive")/rootfs.XXXXXX.tar")
    zstd --decompress --stdout "$rootfs_archive" > "$temporary_tar"
    rootfs_tar=$temporary_tar
else
    rootfs_tar=$rootfs_archive
fi

install -d "$(dirname "$output")"
qemu-img create -q -f qcow2 "$output" "$disk_size"

guestfish --rw -a "$output" <<GUESTFISH
run
debug sh "modprobe dm_thin_pool"
part-init /dev/sda gpt
part-add /dev/sda p 2048 2099199
part-add /dev/sda p 2099200 -34
part-set-gpt-type /dev/sda 1 C12A7328-F81F-11D2-BA4B-00A0C93EC93B
part-set-gpt-type /dev/sda 2 E6D6D379-F507-44C2-A23C-238F2A3DF928
part-set-name /dev/sda 1 "ShenChen EFI"
part-set-name /dev/sda 2 "ShenChen LVM"
mkfs vfat /dev/sda1 label:SCLINUX_EFI
pvcreate /dev/sda2
vgcreate vg0 /dev/sda2
debug sh "lvm lvcreate --yes --type thin-pool --extents 90%FREE --name pool vg0"
debug sh "lvm lvcreate --yes --virtualsize $root_size --thinpool vg0/pool --name root"
debug sh "lvm lvcreate --yes --virtualsize $home_size --thinpool vg0/pool --name home"
mkfs xfs /dev/vg0/root label:SCLINUX_ROOT
mkfs xfs /dev/vg0/home label:SCLINUX_HOME
mount /dev/vg0/root /
mkdir-p /home
mkdir-p /boot/efi
mount /dev/vg0/home /home
mount /dev/sda1 /boot/efi
tar-in "$rootfs_tar" / xattrs:true acls:true
sync
umount-all
GUESTFISH

mapfile -t filesystem_uuids < <(
    guestfish --ro -a "$output" <<GUESTFISH | sed '/^$/d'
run
debug sh "modprobe dm_thin_pool; lvm vgchange -ay vg0 >/dev/null"
vfs-uuid /dev/vg0/root
vfs-uuid /dev/vg0/home
vfs-uuid /dev/sda1
GUESTFISH
)
if [ "${#filesystem_uuids[@]}" -ne 3 ]; then
    echo "error: failed to read filesystem UUIDs from $output" >&2
    exit 1
fi

temporary_fstab=$(mktemp "$(dirname "$rootfs_archive")/fstab.XXXXXX")
printf '%s\n' \
    '# /etc/fstab: generated by tools/assemble-image-libguestfs.sh' \
    "UUID=${filesystem_uuids[0]} / xfs defaults 0 1" \
    "UUID=${filesystem_uuids[1]} /home xfs defaults 0 2" \
    "UUID=${filesystem_uuids[2]} /boot/efi vfat umask=0077 0 2" \
    > "$temporary_fstab"

guestfish --rw -a "$output" <<GUESTFISH
run
debug sh "modprobe dm_thin_pool; lvm vgchange -ay vg0 >/dev/null"
mount /dev/vg0/root /
upload "$temporary_fstab" /etc/fstab
sync
umount-all
GUESTFISH

qemu-img check "$output"
completed=true
echo "assembled $output"
