schema_version = 1

[package]
name = "libarchive"
version = "3.8.9"
release = "2"
description = "bsdtar and bsdcpio archive tools"
license = "BSD-2-Clause"
channel = "system"

[source]
url = "https://github.com/libarchive/libarchive/releases/download/v3.8.9/libarchive-3.8.9.tar.xz"
sha256 = "888c934f9d95648ecb9163dc8e23ab80a476ecb81a8f1154704a227b5b676dde"

dependencies = [
    "libarchive-libs >= 3.8.9"
]

build_dependencies = [
    "pkgconf >= 3.0.5",
    "openssl-dev >= 4.0.1",
    "zlib-dev >= 1.3.2"
]

provides = [
    "libarchive"
]

prepare = []

build = [
    "./configure --prefix=/usr --disable-static --without-xml2 --with-expat --without-cng --with-openssl --with-zlib --with-bz2lib --with-lzma --with-zstd",
    "make -j$(nproc)"
]

install = [
    "make install DESTDIR=$DESTDIR",
    "rm -rf $DESTDIR/usr/include $DESTDIR/usr/lib $DESTDIR/usr/lib64 2>/dev/null || true"
]
