schema_version = 1

[package]
name = "bzip2"
version = "1.0.8"
release = "2"
description = "bzip2/bunzip2/bzcat compression tools"
license = "bzip2-1.0.6"
channel = "system"

[source]
url = "https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
sha256 = "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269"

dependencies = [
    "bzip2-libs >= 1.0.8"
]

provides = [
    "bzip2"
]

prepare = []

build = [
    "make -j$(nproc)"
]

install = [
    "make PREFIX=$DESTDIR/usr install",
    "rm -f $DESTDIR/usr/lib/libbz2.a $DESTDIR/usr/lib/libbz2.so* $DESTDIR/usr/include/bzlib.h",
    "rmdir $DESTDIR/usr/lib $DESTDIR/usr/include 2>/dev/null || true"
]
